/*
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
*/
package org.unitime.timetable.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import org.unitime.timetable.model.base.BaseReliefAssignment;

/**
 * One lesson made vacant by a {@link StaffAbsence} and the relief teacher assigned
 * to cover it. Rows are (re)generated by the relief-generation engine; an
 * administrator may override the relief teacher on the oversight board, which
 * flips the status to {@link Status#MANUAL} so a subsequent regeneration preserves it.
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "relief_assignment")
public class ReliefAssignment extends BaseReliefAssignment {
	private static final long serialVersionUID = 1L;

	public static enum Status {
		UNASSIGNED,	// 0 - no eligible relief teacher was found
		AUTO,		// 1 - assigned automatically by the engine
		MANUAL,		// 2 - set/overridden by an administrator (preserved on regeneration)
		;
		public int value() { return ordinal(); }
		public static Status fromValue(Integer v) {
			return (v == null || v < 0 || v >= values().length) ? UNASSIGNED : values()[v];
		}
	}

	public ReliefAssignment() {
		super();
	}

	public ReliefAssignment(Long uniqueId) {
		super(uniqueId);
	}

	public Status status() { return Status.fromValue(getStatus()); }
	public boolean isManual() { return status() == Status.MANUAL; }
	public boolean isAssigned() { return getReliefUid() != null && !getReliefUid().isEmpty(); }
}
